/*
 FlashCanvas
 Copyright (c) 2012      Willow Systems Corp
 Copyright (c) 2009      Tim Cameron Ryan
 Copyright (c) 2009-2011 FlashCanvas Project
 Released under the MIT/X License
*/
window.ActiveXObject&&!window.CanvasRenderingContext2D&&function(j,l,z){function A(){if("complete"===l.readyState){l.detachEvent(D,A);for(var a=l.getElementsByTagName(r),b=0,c=a.length;b<c;++b)B.initElement(a[b])}}function E(){var a=event.srcElement,b=a.parentNode;a.blur();b.focus()}function F(){var a=event.propertyName;if("width"===a||"height"===a){var b=event.srcElement,c=b[a],d=parseInt(c,10);if(isNaN(d)||0>d)d="width"===a?300:150;c===d?(b.style[a]=d+"px",b.getContext("2d")._resize(b.width,b.height)):
b[a]=d}}function G(){j.detachEvent(H,G);for(var a in n){var b=n[a],c=b.firstChild,d;for(d in c)"function"===typeof c[d]&&(c[d]=i);for(d in b)"function"===typeof b[d]&&(b[d]=i);c.detachEvent(I,E);b.detachEvent(J,F)}j[K]=i;j[L]=i;j[M]=i;j[C]=i;j[N]=i}function s(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;")}function Q(a){return a.toLowerCase()}function k(a){throw new O(a);}function P(a){var b=parseInt(a.width,10),c=parseInt(a.height,10);if(isNaN(b)||0>b)b=300;if(isNaN(c)||0>c)c=150;a.width=
b;a.height=c}var i=null,r="canvas",K="CanvasRenderingContext2D",L="CanvasGradient",M="CanvasPattern",C="FlashCanvas",N="G_vmlCanvasManager",I="onfocus",J="onpropertychange",D="onreadystatechange",H="onunload",h;if(!(h=(j[C+"Options"]||{}).swfPath))h=l.getElementsByTagName("script"),h=h[h.length-1],h=8<=l.documentMode?h.src:h.getAttribute("src",4),h=h.replace(/[^\/]+$/,"");var v=h+"flashcanvas.swf",e=new function(a){for(var b=0,c=a.length;b<c;b++)this[a[b]]=b}("toDataURL save restore scale rotate translate transform setTransform globalAlpha globalCompositeOperation strokeStyle fillStyle createLinearGradient createRadialGradient createPattern lineWidth lineCap lineJoin miterLimit shadowOffsetX shadowOffsetY shadowBlur shadowColor clearRect fillRect strokeRect beginPath closePath moveTo lineTo quadraticCurveTo bezierCurveTo arcTo rect arc fill stroke clip isPointInPath font textAlign textBaseline fillText strokeText measureText drawImage createImageData getImageData putImageData addColorStop direction resize".split(" ")),
t={},p={},q={},w={},n={},x={},u=function(a,b){this.canvas=a;this._swf=b;this._canvasId=b.id.slice(8);this._initialize();this._gradientPatternId=0;this._font=this._direction="";var c=this;setInterval(function(){0===q[c._canvasId]&&c._executeCommand()},30)};u.prototype={save:function(){this._setCompositing();this._setShadows();this._setStrokeStyle();this._setFillStyle();this._setLineStyles();this._setFontStyles();this._stateStack.push([this._globalAlpha,this._globalCompositeOperation,this._strokeStyle,
this._fillStyle,this._lineWidth,this._lineCap,this._lineJoin,this._miterLimit,this._shadowOffsetX,this._shadowOffsetY,this._shadowBlur,this._shadowColor,this._font,this._textAlign,this._textBaseline]);this._queue.push(e.save)},restore:function(){var a=this._stateStack;a.length&&(a=a.pop(),this.globalAlpha=a[0],this.globalCompositeOperation=a[1],this.strokeStyle=a[2],this.fillStyle=a[3],this.lineWidth=a[4],this.lineCap=a[5],this.lineJoin=a[6],this.miterLimit=a[7],this.shadowOffsetX=a[8],this.shadowOffsetY=
a[9],this.shadowBlur=a[10],this.shadowColor=a[11],this.font=a[12],this.textAlign=a[13],this.textBaseline=a[14]);this._queue.push(e.restore)},scale:function(a,b){this._queue.push(e.scale,a,b)},rotate:function(a){this._queue.push(e.rotate,a)},translate:function(a,b){this._queue.push(e.translate,a,b)},transform:function(a,b,c,d,f,g){this._queue.push(e.transform,a,b,c,d,f,g)},setTransform:function(a,b,c,d,f,g){this._queue.push(e.setTransform,a,b,c,d,f,g)},_setCompositing:function(){var a=this._queue;
this._globalAlpha!==this.globalAlpha&&(this._globalAlpha=this.globalAlpha,a.push(e.globalAlpha,this._globalAlpha));this._globalCompositeOperation!==this.globalCompositeOperation&&(this._globalCompositeOperation=this.globalCompositeOperation,a.push(e.globalCompositeOperation,this._globalCompositeOperation))},_setStrokeStyle:function(){if(this._strokeStyle!==this.strokeStyle){var a=this._strokeStyle=this.strokeStyle;if("string"!==typeof a)if(a instanceof m||a instanceof y)a=a.id;else return;this._queue.push(e.strokeStyle,
a)}},_setFillStyle:function(){if(this._fillStyle!==this.fillStyle){var a=this._fillStyle=this.fillStyle;if("string"!==typeof a)if(a instanceof m||a instanceof y)a=a.id;else return;this._queue.push(e.fillStyle,a)}},createLinearGradient:function(a,b,c,d){(!isFinite(a)||!isFinite(b)||!isFinite(c)||!isFinite(d))&&k(9);this._queue.push(e.createLinearGradient,a,b,c,d);return new m(this)},createRadialGradient:function(a,b,c,d,f,g){(!isFinite(a)||!isFinite(b)||!isFinite(c)||!isFinite(d)||!isFinite(f)||!isFinite(g))&&
k(9);(0>c||0>g)&&k(1);this._queue.push(e.createRadialGradient,a,b,c,d,f,g);return new m(this)},createPattern:function(a,b){a||k(17);var c=a.tagName,d,f=this._canvasId;if(c)if(c=c.toLowerCase(),"img"===c)d=a.getAttribute("src",2);else{if(c===r||"video"===c)return;k(17)}else a.src?d=a.src:k(17);"repeat"===b||("no-repeat"===b||"repeat-x"===b||"repeat-y"===b||""===b||b===i)||k(12);this._queue.push(e.createPattern,s(d),b);!p[f][d]&&t[f]&&(this._executeCommand(),++q[f],p[f][d]=!0);return new y(this)},_setLineStyles:function(){var a=
this._queue;this._lineWidth!==this.lineWidth&&(this._lineWidth=this.lineWidth,a.push(e.lineWidth,this._lineWidth));this._lineCap!==this.lineCap&&(this._lineCap=this.lineCap,a.push(e.lineCap,this._lineCap));this._lineJoin!==this.lineJoin&&(this._lineJoin=this.lineJoin,a.push(e.lineJoin,this._lineJoin));this._miterLimit!==this.miterLimit&&(this._miterLimit=this.miterLimit,a.push(e.miterLimit,this._miterLimit))},_setShadows:function(){var a=this._queue;this._shadowOffsetX!==this.shadowOffsetX&&(this._shadowOffsetX=
this.shadowOffsetX,a.push(e.shadowOffsetX,this._shadowOffsetX));this._shadowOffsetY!==this.shadowOffsetY&&(this._shadowOffsetY=this.shadowOffsetY,a.push(e.shadowOffsetY,this._shadowOffsetY));this._shadowBlur!==this.shadowBlur&&(this._shadowBlur=this.shadowBlur,a.push(e.shadowBlur,this._shadowBlur));this._shadowColor!==this.shadowColor&&(this._shadowColor=this.shadowColor,a.push(e.shadowColor,this._shadowColor))},clearRect:function(a,b,c,d){this._queue.push(e.clearRect,a,b,c,d)},fillRect:function(a,
b,c,d){this._setCompositing();this._setShadows();this._setFillStyle();this._queue.push(e.fillRect,a,b,c,d)},strokeRect:function(a,b,c,d){this._setCompositing();this._setShadows();this._setStrokeStyle();this._setLineStyles();this._queue.push(e.strokeRect,a,b,c,d)},beginPath:function(){this._queue.push(e.beginPath)},closePath:function(){this._queue.push(e.closePath)},moveTo:function(a,b){this._queue.push(e.moveTo,a,b)},lineTo:function(a,b){this._queue.push(e.lineTo,a,b)},quadraticCurveTo:function(a,
b,c,d){this._queue.push(e.quadraticCurveTo,a,b,c,d)},bezierCurveTo:function(a,b,c,d,f,g){this._queue.push(e.bezierCurveTo,a,b,c,d,f,g)},arcTo:function(a,b,c,d,f){0>f&&isFinite(f)&&k(1);this._queue.push(e.arcTo,a,b,c,d,f)},rect:function(a,b,c,d){this._queue.push(e.rect,a,b,c,d)},arc:function(a,b,c,d,f,g){0>c&&isFinite(c)&&k(1);this._queue.push(e.arc,a,b,c,d,f,g?1:0)},fill:function(){this._setCompositing();this._setShadows();this._setFillStyle();this._queue.push(e.fill)},stroke:function(){this._setCompositing();
this._setShadows();this._setStrokeStyle();this._setLineStyles();this._queue.push(e.stroke)},clip:function(){this._queue.push(e.clip)},isPointInPath:function(){},_setFontStyles:function(){var a=this._queue;if(this._font!==this.font)try{var b=x[this._canvasId];b.style.font=this._font=this.font;var c=b.currentStyle,d=[c.fontStyle,c.fontWeight,b.offsetHeight,c.fontFamily].join(" ");a.push(e.font,d)}catch(f){}this._textAlign!==this.textAlign&&(this._textAlign=this.textAlign,a.push(e.textAlign,this._textAlign));
this._textBaseline!==this.textBaseline&&(this._textBaseline=this.textBaseline,a.push(e.textBaseline,this._textBaseline));this._direction!==this.canvas.currentStyle.direction&&(this._direction=this.canvas.currentStyle.direction,a.push(e.direction,this._direction))},fillText:function(a,b,c,d){this._setCompositing();this._setFillStyle();this._setShadows();this._setFontStyles();this._queue.push(e.fillText,s(a),b,c,d===z?Infinity:d)},strokeText:function(a,b,c,d){this._setCompositing();this._setStrokeStyle();
this._setShadows();this._setFontStyles();this._queue.push(e.strokeText,s(a),b,c,d===z?Infinity:d)},measureText:function(a){var b=x[this._canvasId];try{b.style.font=this.font}catch(c){}b.innerText=a.replace(/[ \n\f\r]/g,"\t");return new R(b.offsetWidth)},drawImage:function(a,b,c,d,f,g,j,h,l){a||k(17);var i=a.tagName,o,m=arguments.length,n=this._canvasId;if(i)if(i=i.toLowerCase(),"img"===i)o=a.getAttribute("src",2);else{if(i===r||"video"===i)return;k(17)}else a.src?o=a.src:k(17);this._setCompositing();
this._setShadows();o=s(o);if(3===m)this._queue.push(e.drawImage,m,o,b,c);else if(5===m)this._queue.push(e.drawImage,m,o,b,c,d,f);else if(9===m)(0===d||0===f)&&k(1),this._queue.push(e.drawImage,m,o,b,c,d,f,g,j,h,l);else return;!p[n][o]&&t[n]&&(this._executeCommand(),++q[n],p[n][o]=!0)},createImageData:function(){},getImageData:function(){},putImageData:function(){},loadImage:function(a,b,c){var d=a.tagName,f,g=this._canvasId;d?"img"===d.toLowerCase()&&(f=a.getAttribute("src",2)):a.src&&(f=a.src);if(f&&
!p[g][f]){if(b||c)w[g][f]=[a,b,c];this._queue.push(e.drawImage,1,s(f));t[g]&&(this._executeCommand(),++q[g],p[g][f]=!0)}},_initialize:function(){this.globalAlpha=this._globalAlpha=1;this.globalCompositeOperation=this._globalCompositeOperation="source-over";this.fillStyle=this._fillStyle=this.strokeStyle=this._strokeStyle="#000000";this.lineWidth=this._lineWidth=1;this.lineCap=this._lineCap="butt";this.lineJoin=this._lineJoin="miter";this.miterLimit=this._miterLimit=10;this.shadowBlur=this._shadowBlur=
this.shadowOffsetY=this._shadowOffsetY=this.shadowOffsetX=this._shadowOffsetX=0;this.shadowColor=this._shadowColor="rgba(0, 0, 0, 0.0)";this.font=this._font="10px sans-serif";this.textAlign=this._textAlign="start";this.textBaseline=this._textBaseline="alphabetic";this._queue=[];this._stateStack=[]},_flush:function(){var a=this._queue;this._queue=[];return a},_executeCommand:function(){var a=this._flush();if(0<a.length)return eval(this._swf.CallFunction('<invoke name="executeCommand" returntype="javascript"><arguments><string>'+
a.join("&#0;")+"</string></arguments></invoke>"))},_resize:function(a,b){this._executeCommand();this._initialize();0<a&&(this._swf.width=a);0<b&&(this._swf.height=b);this._queue.push(e.resize,a,b)}};var m=function(a){this._ctx=a;this.id=a._gradientPatternId++};m.prototype={addColorStop:function(a,b){(isNaN(a)||0>a||1<a)&&k(1);this._ctx._queue.push(e.addColorStop,this.id,a,b)}};var y=function(a){this.id=a._gradientPatternId++},R=function(a){this.width=a},O=function(a){this.code=a;this.message=S[a]};
O.prototype=Error();var S={1:"INDEX_SIZE_ERR",9:"NOT_SUPPORTED_ERR",11:"INVALID_STATE_ERR",12:"SYNTAX_ERR",17:"TYPE_MISMATCH_ERR",18:"SECURITY_ERR"},B={initElement:function(a){if(a.getContext)return a;var b=Math.random().toString(36).slice(2)||"0",c="external"+b;t[b]=!1;p[b]={};q[b]=1;w[b]={};P(a);a.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+location.protocol+'//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="100%" height="100%" id="'+
c+'"><param name="allowScriptAccess" value="always"><param name="flashvars" value="id='+c+'"><param name="wmode" value="transparent"></object><span style="margin:0;padding:0;border:0;display:inline-block;position:static;height:1em;overflow:visible;white-space:nowrap"></span>';n[b]=a;var d=a.firstChild;x[b]=a.lastChild;var f=l.body.contains;if(f(a))d.movie=v;else var g=setInterval(function(){f(a)&&(clearInterval(g),d.movie=v)},0);if("BackCompat"===l.compatMode||!j.XMLHttpRequest)x[b].style.overflow=
"hidden";var h=new u(a,d);a.getContext=function(a){return"2d"===a?h:i};a.toDataURL=function(a,b){"image/jpeg"===(""+a).replace(/[A-Z]+/g,Q)?h._queue.push(e.toDataURL,a,"number"===typeof b?b:""):h._queue.push(e.toDataURL,a);return h._executeCommand()};d.attachEvent(I,E);return a},saveImage:function(a){a.firstChild.saveImage()},setOptions:function(){},trigger:function(a,b){n[a].fireEvent("on"+b)},unlock:function(a,b,c){var d,e,g;q[a]&&--q[a];if(b===z)d=n[a],b=d.firstChild,P(d),e=d.width,c=d.height,
d.style.width=e+"px",d.style.height=c+"px",0<e&&(b.width=e),0<c&&(b.height=c),b.resize(e,c),d.attachEvent(J,F),t[a]=!0,"function"===typeof d.onload&&setTimeout(function(){d.onload()},0);else if(g=w[a][b])e=g[0],c=g[1+c],delete w[a][b],"function"===typeof c&&c.call(e)}};l.createElement(r);l.createStyleSheet().cssText=r+"{display:inline-block;overflow:hidden;width:300px;height:150px}";"complete"===l.readyState?A():l.attachEvent(D,A);j.attachEvent(H,G);0===v.indexOf(location.protocol+"//"+location.host+
"/")&&(h=new ActiveXObject("Microsoft.XMLHTTP"),h.open("GET",v,!1),h.send(i));j[K]=u;j[L]=m;j[M]=y;j[C]=B;j[N]={init:function(){},init_:function(){},initElement:B.initElement};keep=[u.measureText,u.loadImage]}(window,document);